### ISSUE TITLE
It displays time zone offset when using :date_only=>false

### ISSUE THREAD

**Issue by mprokopov** [jgraichen/rails-timeago#32]
For example with russian locale it will show string like this "Пт, 24 апр. 2015, 12:54:29 +0300". But it seems more convenient way not to show time offset by default.

**Comment by jgraichen** [comment]
*rails-timeago* uses `I18n.l` to localize the date. It does not have it's own "default" time format.

You can configure the localize format key (e.g. `short`, `long`, defaults to `default`) using the `format` option. Otherwise you have to change your locale file defining the date format.
