### ISSUE TITLE
Getting wrong time in when used with action cable

### ISSUE THREAD

**Issue by suramai** [jgraichen/rails-timeago#37]
I am getting two hours ago for new messaged when used with Action cable.
```
<div class="message">    
<div class="media">
  <div>
    <%= link_to image_tag(message.user.avatar.url(:mini), :class => "pull-left media-left img-circle"), message.user %>
  </div>
  <div class="media-body">
      <%= link_to message.user.name, message.user, :class => "footerlinkhover" if message.user %>
      <%= message.body %>
      <span class="chattime">
          <%#= time_ago_in_words(message.created_at).gsub('about','') %>
          <i><%= timeago_tag (message.created_at), :nojs => true, :limit => 10.days.ago %></i>
      </span>
  </div>
</div>
</div>
```

![image](https://cloud.githubusercontent.com/assets/4159214/16168540/197447fe-34d8-11e6-95f5-dd44ed7f3f43.png)

This is after refreshing the page.

![image](https://cloud.githubusercontent.com/assets/4159214/16168547/4ce8e8a6-34d8-11e6-9f95-6b1b11c22bb9.png)

**Comment by jgraichen** [comment]
Can you please test what happens when you drop `:nojs => true`.

I assume the updated content is not activated on jquery-timeago and you're only showing the server-side rendered timestamp with a broken timezone?

You can also manually activate the timeago tag using something like this:
```
function onUpdate(...) {
    // ...
    $('time[data-time-ago]').timeago();
}
```

**Comment by suramai** [comment]
Solved. Thank you so much. :)
