### ISSUE TITLE
Incorrect time ago text

### ISSUE THREAD

**Issue by iamdriz** [jgraichen/rails-timeago#38]
If the current time is: `2016-06-27 15:33:00 UTC`

And the article was posted at `2016-06-27 15:02:26 UTC`

I am getting: `<time datetime="2016-06-27T15:02:26Z" title="Mon, 27 Jun 2016 15:02:26 +0000" data-time-ago="2016-06-27T15:02:26Z">about 17 hours</time>`

As you can see the `datetime` and `title` is correct but the inner text is saying 17 hours... Why is this? The current time is being rendered on the same view using `Time.zone.now` so that's correct, but for some reason the gem thinks it's 17 hours different :/

Here is the code:

`<%= timeago_tag article.created_at, :nojs => true, :limit => 10.days.ago %>`

I'm using this inside an each loop and I've also noticed that ALL of the articles are saying 17 hours...

Here is the full code:

```
<% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article_path(article) %></td>
        <td><%= timeago_tag article.created_at, :nojs => true, :limit => 10.days.ago %><br><%= article.created_at %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article_path(article),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
```

In fact EVEN if I use:

`<%= timeago_tag Time.zone.now, :nojs => true, :limit => 10.days.ago %>`

outside of the each loop, I am still seeing 17 hours! So it seems that the helper is confused how to work out the time ago (without the JS). And the loop isn't the reason because this with just the `Time.zone.now` and outside of it.

**Comment by samvandamme** [comment]
Having the same issue when a `timeago_tag` is rendered via ActionCable...

**Comment by ollieh-m** [comment]
With JS disabled, `nojs: true` will display the distance in time from 00:00 on timestamp's date, but `date_only` is true by default. So you probably want:
```
<%= timeago_tag(timestamp, nojs: true, date_only: false) %>
```

It'd be nice if that appended 'ago' to the string, but it doesn't...

**Comment by jgraichen** [comment]
The gem uses Rails own [`#time_ago_in_words`](https://api.rubyonrails.org/v5.2/classes/ActionView/Helpers/DateHelper.html#method-i-time_ago_in_words) when `nojs: true` is set. This method depends on properly loaded timestamps with configured time zones. Please test with `#time_ago_in_words` how your code behaves without JS. Please check if your server is e.g. running in UTC timezone. Localization ('ago' or not) is provided by rails-i18n and your locale files. If you want different wordings you need to change it there.

I do not recommend to ever use `nojs: true`. Users without JavaScript will only ever see *wrong* times as they are not updated as time passes. I always recommend to only print absolute dates and times as the non-JS fallback.

**Comment by samvandamme** [comment]
For those interested, I fixed this by setting `$('time[data-time-ago]').timeago();` at the end of my `actioncable.subscriptions received` code.
