### ISSUE TITLE
timeago does not run in production

### ISSUE THREAD

**Issue by rickyhopkins** [jgraichen/rails-timeago#39]
I have included this gem into my project and it works great until it hits production.

application.js:

```
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require bootstrap
//= require rails-timeago
//= require_tree .
```

I change a setting to allow future dates using:
`$.timeago.settings.allowFuture = true;`

This works in dev but when it hits heroku in either stage or production timeago cannot be found.

I can see that the plugin is included in my compiled js file but it does not seem to be attached to the `$` object

**Comment by rickyhopkins** [comment]
Probably should have mentioned that I am using rails 5

**Comment by jgraichen** [comment]
Does something mangle your global symbols?

Because the initializing JavaScript is using the `jQuery` symbol:

```javascript
(function(...) {
	
})(jQuery);
```
