### ISSUE TITLE
Timeago fails to work in incognito Chrome mode

### ISSUE THREAD

**Issue by vholovatyy** [jgraichen/rails-timeago#41]
I am getting kind of weird bug with TimeAgo Rails.

So, given `<%= timeago_tag Time.now, nojs: true, class: 'timeago-time', limit: nil %>` every other browser works fine, producing `6 minutes ago` and so on. BUT Chrome + incognito more on iPhone is behaving in a strange way: I am getting 1) `about 14 hours` 2) without a word `ago`

Please help me to deal with it. What is the possible fix here?

**Comment by jgraichen** [comment]
This sounds like you have JavaScript disabled and are seeing the server-side rendered text due to having `nojs: true` set. I do not recommend using `nojs: true`.

Try setting `nojs` to `false`. If you see a date instead of a timeago text you have JavaScript disabled or there is a JavaScript error.
