### ISSUE TITLE
Timeago helper not working without setting up helper or initializer

### ISSUE THREAD

**Issue by yengfinity** [jgraichen/rails-timeago#42]
When this gem is first install on a Rails 5.1.6, it wasn't clear that I had to add to timeago helper:
```
Rails::Timeago.default_options :limit => proc { 20.days.ago }, :nojs => true
```

It was difficult to figure this out right away.  It'll be nice to have a generator to make it easier for users to install and plug in the helper.

**Comment by pdxmike** [comment]
> When this gem is first install on a Rails 5.1.6, it wasn't clear that I had to add to timeago helper:
> 
> ```
> Rails::Timeago.default_options :limit => proc { 20.days.ago }, :nojs => true
> ```
> It was difficult to figure this out right away. It'll be nice to have a generator to make it easier for users to install and plug in the helper.

I'm still a junior-esque dev and was a little confused at first by this, as well.   I submitted a pull request to add a little clarity in the README for future users.

**Comment by jgraichen** [comment]
The plugin does work without any additional configuration if setup as described in the README. 

I do not recommend ever using `nojs: true`, as it will generate the time difference in words on the server! If your JavaScript is broken, it appears to be correct, but the words are never updated.

See the demo application [here](https://github.com/jgraichen/rails-timeago-demo-6) about using rails-timeago with Rails 6 and sprockets. When using rails-timeago with webpacker, you need to setup the JavaScript plugin yourself.
