### ISSUE TITLE
Is this integration available for Ruby => 3 and RoR => 6?

### ISSUE THREAD

**Issue by axelmukwena** [jgraichen/rails-timeago#48]
As explained here, https://stackoverflow.com/questions/66521276/rails-timeago-gem-not-showing, I'm unable to configure the integration. My assumption would be incompatibility

**Comment by jgraichen** [comment]
This project is tested with Ruby 3.0 and Rails 6+ and works fine. Please note, the install instructions are for sprockets, not webpacker. If you use webpacker, you need to setup the JavaScript on your own.

**Comment by axelmukwena** [comment]
Ah, that explains it then. Thank you
